name: "🤺 Add a character"
title: "[AC] <character name>"
description: "You created a character and you want to send it in the Armus."
labels:
  - "AddCharacter"
body:
  - type: markdown
    attributes:
      value: |
        # 🤺 Add a character
  - type: input
    attributes:
      label: "Character name:"
      description: "Write the name of the character you want to submit"
      placeholder: "ex. abigus"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Image"
      description: "You can send the image by uploading it on a service like Imgur and by pasting the link below, or you can upload it in the box below."
      placeholder: "Paste the URL, or upload the image by tapping \"Attach files...\" below, or use Drag and Drop."
    validations:
      required: true
  - type: input
    attributes:
      label: "Your name in the Acknowledgements"
      description: "This is the name you want to be called by in the `🌟 Acknowledgements` section of the main page."
      placeholder: "ex. Apix"
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: "Send your character"
      description: "By sending your character, you swear that you are the rightful owner of the image, that you have not obtained it through any means that infringe upon the intellectual property rights of any third party, and that you are willingly giving the image to the project for its use."
      options:
        - label: "I attest ownership and grant the use of the image I am sending."
          required: true